language: java

jdk:
  - oraclejdk8

script: mvn clean install -Pbuild

deploy:
  -
    provider: script
    script: gpg2 --keyserver keyserver.ubuntu.com  --recv-keys $PGP_KEYNAME
    skip_cleanup: true
    on:
      branch: deploy
      tags: false
