language: java

jdk:
  - oraclejdk8

script: mvn clean install -Pbuild

deploy:
    provider: script
    script: mvn deploy --settings .travis/settings.xml
    skip_cleanup: true
    all_branches: true
